build: false
platform: x86
clone_folder: c:\projects\symfony\panther

cache:
  - '%LOCALAPPDATA%\Composer\files'

matrix:
  - PHP_VERSION: 7.1.7
    VERSION: 71
  - PHP_VERSION: 7.2.8
    VERSION: 72

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst -y php --version %PHP_VERSION% composer googlechrome
  - refreshenv
  - cd c:\tools\php%VERSION%
  - copy php.ini-production php.ini /Y
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo memory_limit=3G >> php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  - composer install --no-interaction --no-progress

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - php vendor\phpunit\phpunit\phpunit
